import type { CalendarEventView } from './events-api';

export const demoEvents: CalendarEventView[] = [
  {
    id: 'designing-with-ai',
    title: 'Designing with AI',
    description:
      'A practical evening on turning rough ideas into thoughtful products, with demos and an open Q&A.',
    startAt: '2026-09-03T11:00:00.000Z',
    endAt: '2026-09-03T12:30:00.000Z',
    eventDate: '2026-09-03',
    timezone: 'Asia/Singapore',
    allDay: false,
    locationName: 'The Foundry',
    address: '11 Prinsep Link, Singapore',
    rsvpUrl: 'https://example.com/designing-with-ai',
    sourceLabel: 'Designers SG',
    status: 'confirmed',
  },
  {
    id: 'founders-breakfast',
    title: 'Founders breakfast',
    description: 'A small, informal breakfast for early-stage founders.',
    startAt: '2026-09-08T00:30:00.000Z',
    endAt: '2026-09-08T02:00:00.000Z',
    eventDate: '2026-09-08',
    timezone: 'Asia/Singapore',
    allDay: false,
    locationName: 'Common Man Coffee Roasters',
    address: '22 Martin Road, Singapore',
    rsvpUrl: null,
    sourceLabel: 'SG Builders',
    status: 'confirmed',
  },
  {
    id: 'noc-sharing',
    title: 'NOC Alumni Sharing Night',
    description:
      'Hear candid stories from recent NOC alumni and meet students considering the programme.',
    startAt: '2026-09-10T11:00:00.000Z',
    endAt: '2026-09-10T13:00:00.000Z',
    eventDate: '2026-09-10',
    timezone: 'Asia/Singapore',
    allDay: false,
    locationName: 'NUS Enterprise',
    address: '71 Ayer Rajah Crescent, Singapore',
    rsvpUrl: 'https://example.com/noc-sharing',
    sourceLabel: 'NUS Overseas Colleges',
    status: 'unconfirmed',
  },
  {
    id: 'product-office-hours',
    title: 'Product office hours',
    description: 'Bring one product problem and leave with a clearer next step.',
    startAt: '2026-09-15T04:00:00.000Z',
    endAt: '2026-09-15T05:00:00.000Z',
    eventDate: '2026-09-15',
    timezone: 'Asia/Singapore',
    allDay: false,
    locationName: 'Online',
    address: null,
    rsvpUrl: null,
    sourceLabel: 'Product Folks SG',
    status: 'unconfirmed',
  },
  {
    id: 'hack-weekend',
    title: 'Civic tech hack weekend',
    description: 'A weekend build sprint for tools that make city life easier.',
    startAt: null,
    endAt: null,
    eventDate: '2026-09-19',
    timezone: 'Asia/Singapore',
    allDay: true,
    locationName: 'Open Government Products',
    address: 'Singapore',
    rsvpUrl: 'https://example.com/civic-tech',
    sourceLabel: 'Tech for Good',
    status: 'confirmed',
  },
  {
    id: 'climate-meetup',
    title: 'Climate coffee meetup',
    description: 'Coffee and conversations for people working on climate solutions.',
    startAt: '2026-09-24T10:30:00.000Z',
    endAt: '2026-09-24T12:00:00.000Z',
    eventDate: '2026-09-24',
    timezone: 'Asia/Singapore',
    allDay: false,
    locationName: 'City Sprouts',
    address: '102 Henderson Road, Singapore',
    rsvpUrl: null,
    sourceLabel: 'Climate SG',
    status: 'unconfirmed',
  },
  {
    id: 'creative-mornings',
    title: 'CreativeMornings: Tempo',
    description: 'A breakfast talk exploring the month’s theme: Tempo.',
    startAt: '2026-09-30T00:00:00.000Z',
    endAt: '2026-09-30T01:30:00.000Z',
    eventDate: '2026-09-30',
    timezone: 'Asia/Singapore',
    allDay: false,
    locationName: 'National Design Centre',
    address: '111 Middle Road, Singapore',
    rsvpUrl: null,
    sourceLabel: 'CreativeMornings SG',
    status: 'confirmed',
  },
];
